lp:
  name: Laydown Process
  id: 1
  config:
    datasource:
      username: ${LP_PSQL_DB_USER}
      password: ${LP_PSQL_DB_PWD}
      jdbc-url: ${POSTGRESQLCONNSTR_LP_PSQL_DB_URL}
      driverClassName: org.postgresql.Driver
      maximumPoolSize: 3
spring:
  profiles:
    active: ${LP_PROFILES}
  mvc:
    converters:
      preferred-json-mapper: gson
logging:
  level:
    org.springframework.boot.autoconfigure: error
server:
  port: 9970
  servlet:
    context-path: /lp-api
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: ${LOCALHOST_CERT}
    key-store-password: ${LOCALHOST_CERT_PWD}
